// Plan Comptable SYSCOHADA révisé (AUDCIF 2017) — extrait opérationnel BTP
// Liste non exhaustive : couvre les comptes courants d'une SARL BTP en CI.
// Étendre selon besoins en ajoutant des subdivisions (ex. 6012xx pour matières).

import { ClasseCompte, SensCompte } from "@prisma/client";

export interface PlanCompteSeed {
  numero: string;
  libelle: string;
  classe: ClasseCompte;
  sensNormal: SensCompte;
  lettrable?: boolean;
  auxiliaire?: boolean;
}

export const PLAN_COMPTABLE: PlanCompteSeed[] = [
  // ========== CLASSE 1 — Ressources durables ==========
  { numero: "101000", libelle: "Capital social", classe: "C1", sensNormal: "CREDIT" },
  { numero: "104600", libelle: "Primes d'émission", classe: "C1", sensNormal: "CREDIT" },
  { numero: "106000", libelle: "Réserves", classe: "C1", sensNormal: "CREDIT" },
  { numero: "110000", libelle: "Report à nouveau (créditeur)", classe: "C1", sensNormal: "CREDIT" },
  { numero: "129000", libelle: "Report à nouveau (débiteur)", classe: "C1", sensNormal: "DEBIT" },
  { numero: "130000", libelle: "Résultat net de l'exercice", classe: "C1", sensNormal: "MIXTE" },
  { numero: "161000", libelle: "Emprunts obligataires", classe: "C1", sensNormal: "CREDIT" },
  { numero: "162000", libelle: "Emprunts auprès des établissements de crédit", classe: "C1", sensNormal: "CREDIT" },
  { numero: "164000", libelle: "Avances reçues de l'État", classe: "C1", sensNormal: "CREDIT" },
  { numero: "168000", libelle: "Autres emprunts et dettes", classe: "C1", sensNormal: "CREDIT" },
  { numero: "191000", libelle: "Provisions pour litiges", classe: "C1", sensNormal: "CREDIT" },

  // ========== CLASSE 2 — Actif immobilisé ==========
  { numero: "211000", libelle: "Terrains", classe: "C2", sensNormal: "DEBIT" },
  { numero: "213000", libelle: "Bâtiments", classe: "C2", sensNormal: "DEBIT" },
  { numero: "231000", libelle: "Bâtiments en cours", classe: "C2", sensNormal: "DEBIT" },
  { numero: "241100", libelle: "Matériel et outillage BTP", classe: "C2", sensNormal: "DEBIT" },
  { numero: "244000", libelle: "Matériel et mobilier de bureau", classe: "C2", sensNormal: "DEBIT" },
  { numero: "245000", libelle: "Matériel de transport", classe: "C2", sensNormal: "DEBIT" },
  { numero: "2813000", libelle: "Amortissements des bâtiments", classe: "C2", sensNormal: "CREDIT" },
  { numero: "2841000", libelle: "Amortissements matériel et outillage", classe: "C2", sensNormal: "CREDIT" },
  { numero: "2845000", libelle: "Amortissements matériel de transport", classe: "C2", sensNormal: "CREDIT" },

  // ========== CLASSE 3 — Stocks ==========
  { numero: "311000", libelle: "Matières premières (ciment, fer, agrégats)", classe: "C3", sensNormal: "DEBIT" },
  { numero: "321000", libelle: "Matières consommables", classe: "C3", sensNormal: "DEBIT" },
  { numero: "335000", libelle: "Travaux en cours", classe: "C3", sensNormal: "DEBIT" },
  { numero: "385000", libelle: "Marchandises en cours de route", classe: "C3", sensNormal: "DEBIT" },

  // ========== CLASSE 4 — Tiers ==========
  { numero: "401000", libelle: "Fournisseurs, dettes en compte", classe: "C4", sensNormal: "CREDIT", lettrable: true, auxiliaire: true },
  { numero: "4011000", libelle: "Fournisseurs locaux", classe: "C4", sensNormal: "CREDIT", lettrable: true, auxiliaire: true },
  { numero: "4012000", libelle: "Fournisseurs étrangers (Groupe Zone UEMOA)", classe: "C4", sensNormal: "CREDIT", lettrable: true, auxiliaire: true },
  { numero: "402000", libelle: "Fournisseurs, effets à payer", classe: "C4", sensNormal: "CREDIT", lettrable: true },
  { numero: "404000", libelle: "Fournisseurs d'investissements", classe: "C4", sensNormal: "CREDIT", lettrable: true, auxiliaire: true },
  { numero: "408100", libelle: "Fournisseurs, factures non parvenues", classe: "C4", sensNormal: "CREDIT" },
  { numero: "409100", libelle: "Fournisseurs, avances et acomptes versés", classe: "C4", sensNormal: "DEBIT", lettrable: true },
  { numero: "411000", libelle: "Clients", classe: "C4", sensNormal: "DEBIT", lettrable: true, auxiliaire: true },
  { numero: "4111000", libelle: "Clients locaux", classe: "C4", sensNormal: "DEBIT", lettrable: true, auxiliaire: true },
  { numero: "4112000", libelle: "Clients État et collectivités", classe: "C4", sensNormal: "DEBIT", lettrable: true, auxiliaire: true },
  { numero: "412000", libelle: "Clients, effets à recevoir", classe: "C4", sensNormal: "DEBIT", lettrable: true },
  { numero: "414000", libelle: "Créances sur cessions d'immobilisations", classe: "C4", sensNormal: "DEBIT", lettrable: true },
  { numero: "416000", libelle: "Créances clients litigieuses ou douteuses", classe: "C4", sensNormal: "DEBIT", lettrable: true },
  { numero: "418100", libelle: "Clients, factures à établir", classe: "C4", sensNormal: "DEBIT" },
  { numero: "419100", libelle: "Clients, avances et acomptes reçus", classe: "C4", sensNormal: "CREDIT", lettrable: true },
  { numero: "419700", libelle: "Clients, retenue de garantie", classe: "C4", sensNormal: "CREDIT", lettrable: true },
  { numero: "421000", libelle: "Personnel, avances et acomptes", classe: "C4", sensNormal: "DEBIT" },
  { numero: "422000", libelle: "Personnel, rémunérations dues", classe: "C4", sensNormal: "CREDIT" },
  { numero: "423000", libelle: "Personnel, oppositions", classe: "C4", sensNormal: "CREDIT" },
  { numero: "431000", libelle: "Sécurité sociale (CNPS)", classe: "C4", sensNormal: "CREDIT" },
  { numero: "4311000", libelle: "CNPS — cotisations salariales", classe: "C4", sensNormal: "CREDIT" },
  { numero: "4312000", libelle: "CNPS — cotisations patronales", classe: "C4", sensNormal: "CREDIT" },
  { numero: "4313000", libelle: "CNPS — accident du travail", classe: "C4", sensNormal: "CREDIT" },
  { numero: "441000", libelle: "État, impôts sur les bénéfices (IS/BIC)", classe: "C4", sensNormal: "CREDIT" },
  { numero: "442000", libelle: "État, autres impôts et taxes", classe: "C4", sensNormal: "CREDIT" },
  { numero: "4421000", libelle: "État — Patente / TEE", classe: "C4", sensNormal: "CREDIT" },
  { numero: "4422000", libelle: "État — Impôts fonciers", classe: "C4", sensNormal: "CREDIT" },
  { numero: "4423000", libelle: "État — IRVM", classe: "C4", sensNormal: "CREDIT" },
  { numero: "4424000", libelle: "État — TOB", classe: "C4", sensNormal: "CREDIT" },
  { numero: "4425000", libelle: "État — FDFP (taxe d'apprentissage + formation)", classe: "C4", sensNormal: "CREDIT" },
  { numero: "4426000", libelle: "État — ITS retenu à la source", classe: "C4", sensNormal: "CREDIT" },
  { numero: "4427000", libelle: "État — AIRSI / retenue à la source BTP", classe: "C4", sensNormal: "CREDIT" },
  { numero: "443100", libelle: "État, TVA facturée (collectée)", classe: "C4", sensNormal: "CREDIT" },
  { numero: "445200", libelle: "État, TVA récupérable sur immobilisations", classe: "C4", sensNormal: "DEBIT" },
  { numero: "445300", libelle: "État, TVA récupérable sur autres biens et services", classe: "C4", sensNormal: "DEBIT" },
  { numero: "445700", libelle: "État, crédit de TVA à reporter", classe: "C4", sensNormal: "DEBIT" },
  { numero: "4449000", libelle: "État, TVA à décaisser", classe: "C4", sensNormal: "CREDIT" },
  { numero: "465000", libelle: "Associés, dividendes à payer", classe: "C4", sensNormal: "CREDIT" },
  { numero: "467000", libelle: "Compte courant associés", classe: "C4", sensNormal: "MIXTE" },
  { numero: "471000", libelle: "Débiteurs divers", classe: "C4", sensNormal: "DEBIT" },
  { numero: "472000", libelle: "Créditeurs divers", classe: "C4", sensNormal: "CREDIT" },
  { numero: "476000", libelle: "Charges constatées d'avance", classe: "C4", sensNormal: "DEBIT" },
  { numero: "477000", libelle: "Produits constatés d'avance", classe: "C4", sensNormal: "CREDIT" },
  { numero: "486000", libelle: "Charges à répartir sur plusieurs exercices", classe: "C4", sensNormal: "DEBIT" },

  // ========== CLASSE 5 — Trésorerie ==========
  { numero: "502000", libelle: "Actions propres", classe: "C5", sensNormal: "DEBIT" },
  { numero: "511000", libelle: "Chèques à encaisser", classe: "C5", sensNormal: "DEBIT" },
  { numero: "521100", libelle: "Banques locales — compte principal", classe: "C5", sensNormal: "MIXTE" },
  { numero: "521200", libelle: "Banque — compte secondaire", classe: "C5", sensNormal: "MIXTE" },
  { numero: "531000", libelle: "Chèques postaux", classe: "C5", sensNormal: "MIXTE" },
  { numero: "551000", libelle: "Caisse principale — siège", classe: "C5", sensNormal: "DEBIT" },
  { numero: "552000", libelle: "Caisse chantier", classe: "C5", sensNormal: "DEBIT" },
  { numero: "561100", libelle: "Mobile Money — Orange Money", classe: "C5", sensNormal: "DEBIT" },
  { numero: "561200", libelle: "Mobile Money — MTN MoMo", classe: "C5", sensNormal: "DEBIT" },
  { numero: "561300", libelle: "Mobile Money — Wave", classe: "C5", sensNormal: "DEBIT" },
  { numero: "561400", libelle: "Mobile Money — Moov Money", classe: "C5", sensNormal: "DEBIT" },
  { numero: "581000", libelle: "Virements internes", classe: "C5", sensNormal: "MIXTE" },

  // ========== CLASSE 6 — Charges ==========
  { numero: "601100", libelle: "Achats de matières premières (ciment, fer, sable)", classe: "C6", sensNormal: "DEBIT" },
  { numero: "601200", libelle: "Achats de matières consommables", classe: "C6", sensNormal: "DEBIT" },
  { numero: "604000", libelle: "Achats stockés de matières et fournitures liées", classe: "C6", sensNormal: "DEBIT" },
  { numero: "605000", libelle: "Autres achats (eau, électricité, carburant chantier)", classe: "C6", sensNormal: "DEBIT" },
  { numero: "6051000", libelle: "Eau", classe: "C6", sensNormal: "DEBIT" },
  { numero: "6052000", libelle: "Électricité", classe: "C6", sensNormal: "DEBIT" },
  { numero: "6053000", libelle: "Carburant et lubrifiants", classe: "C6", sensNormal: "DEBIT" },
  { numero: "6055000", libelle: "Fournitures de bureau", classe: "C6", sensNormal: "DEBIT" },
  { numero: "608000", libelle: "Achats d'emballages", classe: "C6", sensNormal: "DEBIT" },
  { numero: "611000", libelle: "Transports sur achats", classe: "C6", sensNormal: "DEBIT" },
  { numero: "612000", libelle: "Transports sur ventes", classe: "C6", sensNormal: "DEBIT" },
  { numero: "613000", libelle: "Locations et charges locatives", classe: "C6", sensNormal: "DEBIT" },
  { numero: "6131000", libelle: "Location bureaux / siège", classe: "C6", sensNormal: "DEBIT" },
  { numero: "6132000", libelle: "Location matériel BTP / engins", classe: "C6", sensNormal: "DEBIT" },
  { numero: "614000", libelle: "Entretien, réparations et maintenance", classe: "C6", sensNormal: "DEBIT" },
  { numero: "616000", libelle: "Primes d'assurance", classe: "C6", sensNormal: "DEBIT" },
  { numero: "622000", libelle: "Rémunérations d'intermédiaires et conseils", classe: "C6", sensNormal: "DEBIT" },
  { numero: "6228000", libelle: "Honoraires (expert-comptable, avocat, notaire)", classe: "C6", sensNormal: "DEBIT" },
  { numero: "624000", libelle: "Sous-traitance générale (BTP)", classe: "C6", sensNormal: "DEBIT" },
  { numero: "625000", libelle: "Publicité, publications, relations publiques", classe: "C6", sensNormal: "DEBIT" },
  { numero: "626000", libelle: "Frais de télécommunications", classe: "C6", sensNormal: "DEBIT" },
  { numero: "627000", libelle: "Services bancaires", classe: "C6", sensNormal: "DEBIT" },
  { numero: "628000", libelle: "Cotisations et dons", classe: "C6", sensNormal: "DEBIT" },
  { numero: "631000", libelle: "Frais de transports du personnel", classe: "C6", sensNormal: "DEBIT" },
  { numero: "632000", libelle: "Frais de mission, réception, déplacements", classe: "C6", sensNormal: "DEBIT" },
  { numero: "641000", libelle: "Impôts et taxes directs — Patente / TEE", classe: "C6", sensNormal: "DEBIT" },
  { numero: "6411000", libelle: "Patente / TEE", classe: "C6", sensNormal: "DEBIT" },
  { numero: "6412000", libelle: "Impôts fonciers", classe: "C6", sensNormal: "DEBIT" },
  { numero: "6414000", libelle: "TOB", classe: "C6", sensNormal: "DEBIT" },
  { numero: "6415000", libelle: "FDFP — taxe apprentissage et formation continue", classe: "C6", sensNormal: "DEBIT" },
  { numero: "646000", libelle: "Droits d'enregistrement et timbre", classe: "C6", sensNormal: "DEBIT" },
  { numero: "647000", libelle: "Pénalités et amendes fiscales / pénales", classe: "C6", sensNormal: "DEBIT" },
  { numero: "661000", libelle: "Rémunérations directes versées au personnel national", classe: "C6", sensNormal: "DEBIT" },
  { numero: "6611000", libelle: "Salaires de base", classe: "C6", sensNormal: "DEBIT" },
  { numero: "6612000", libelle: "Primes et indemnités", classe: "C6", sensNormal: "DEBIT" },
  { numero: "6613000", libelle: "Main d'œuvre occasionnelle (tâcherons)", classe: "C6", sensNormal: "DEBIT" },
  { numero: "664000", libelle: "Charges sociales (CNPS patronale, AT)", classe: "C6", sensNormal: "DEBIT" },
  { numero: "671000", libelle: "Intérêts des emprunts", classe: "C6", sensNormal: "DEBIT" },
  { numero: "674000", libelle: "Autres charges financières", classe: "C6", sensNormal: "DEBIT" },
  { numero: "681000", libelle: "Dotations aux amortissements d'exploitation", classe: "C6", sensNormal: "DEBIT" },
  { numero: "691000", libelle: "Dotations aux provisions d'exploitation", classe: "C6", sensNormal: "DEBIT" },

  // ========== CLASSE 7 — Produits ==========
  { numero: "701000", libelle: "Ventes de marchandises", classe: "C7", sensNormal: "CREDIT" },
  { numero: "704000", libelle: "Travaux facturés (BTP — bâtiment)", classe: "C7", sensNormal: "CREDIT" },
  { numero: "7041000", libelle: "Travaux — construction neuve", classe: "C7", sensNormal: "CREDIT" },
  { numero: "7042000", libelle: "Travaux — rénovation", classe: "C7", sensNormal: "CREDIT" },
  { numero: "7043000", libelle: "Travaux publics (routes, ponts, VRD)", classe: "C7", sensNormal: "CREDIT" },
  { numero: "7044000", libelle: "Travaux spécialisés (plomberie, électricité, peinture)", classe: "C7", sensNormal: "CREDIT" },
  { numero: "706000", libelle: "Services vendus (planification, gestion de chantier)", classe: "C7", sensNormal: "CREDIT" },
  { numero: "707000", libelle: "Produits accessoires (location matériel)", classe: "C7", sensNormal: "CREDIT" },
  { numero: "708000", libelle: "Autres revenus", classe: "C7", sensNormal: "CREDIT" },
  { numero: "719000", libelle: "Rabais, remises et ristournes accordés", classe: "C7", sensNormal: "DEBIT" },
  { numero: "734000", libelle: "Variation des stocks de produits (travaux en cours)", classe: "C7", sensNormal: "MIXTE" },
  { numero: "758000", libelle: "Produits divers", classe: "C7", sensNormal: "CREDIT" },
  { numero: "771000", libelle: "Intérêts de prêts", classe: "C7", sensNormal: "CREDIT" },
  { numero: "781000", libelle: "Reprises d'amortissements", classe: "C7", sensNormal: "CREDIT" },
  { numero: "791000", libelle: "Reprises de provisions", classe: "C7", sensNormal: "CREDIT" },

  // ========== CLASSE 8 — HAO ==========
  { numero: "811000", libelle: "Valeurs comptables des cessions d'immobilisations", classe: "C8", sensNormal: "DEBIT" },
  { numero: "822000", libelle: "Produits de cessions d'immobilisations", classe: "C8", sensNormal: "CREDIT" },
  { numero: "831000", libelle: "Charges HAO", classe: "C8", sensNormal: "DEBIT" },
  { numero: "841000", libelle: "Produits HAO", classe: "C8", sensNormal: "CREDIT" },
  { numero: "891000", libelle: "Impôts sur les sociétés (IS)", classe: "C8", sensNormal: "DEBIT" },
];
